sudo: false
language: go

go:
  - 1.6
  - 1.7
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go get gopkg.in/check.v1
  - mkdir -p $HOME/gopath/src/gopkg.in/vmihailenco
  - mv `pwd` $HOME/gopath/src/github.com/liangdas/mqant/utils/msgpack.v2
